name: kickstarter
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - flask=*
  - jinja2=*
  - numpy=*
  - pandas=*
  - scikit-learn=*
  - category_encoders=*
  - matplotlib=*
  - pip=*
  - pip:
    - gunicorn

